// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function AttachTarget(arg1:string,arg2:string):Promise<gui.OperationResult>;

export function CleanupEventHistory(arg1:number):Promise<gui.OperationResult>;

export function CloseBrowser():Promise<gui.OperationResult>;

export function CreateNewConfig(arg1:string):Promise<gui.NewConfigResult>;

export function DeleteConfig(arg1:number):Promise<gui.OperationResult>;

export function DetachTarget(arg1:string,arg2:string):Promise<gui.OperationResult>;

export function DisableInterception(arg1:string):Promise<gui.OperationResult>;

export function EnableInterception(arg1:string):Promise<gui.OperationResult>;

export function ExportConfig(arg1:string,arg2:string):Promise<gui.OperationResult>;

export function GenerateNewRule(arg1:string,arg2:number):Promise<gui.NewRuleResult>;

export function GetActiveConfig():Promise<gui.ConfigResult>;

export function GetAllSettings():Promise<gui.SettingsResult>;

export function GetBrowserStatus():Promise<gui.LaunchBrowserResult>;

export function GetConfig(arg1:number):Promise<gui.ConfigResult>;

export function GetCurrentSession():Promise<string>;

export function GetEventStats():Promise<gui.EventStatsResult>;

export function GetRuleStats(arg1:string):Promise<gui.StatsResult>;

export function GetSetting(arg1:string):Promise<string>;

export function ImportConfig(arg1:string):Promise<gui.ConfigResult>;

export function LaunchBrowser(arg1:boolean):Promise<gui.LaunchBrowserResult>;

export function ListConfigs():Promise<gui.ConfigListResult>;

export function ListTargets(arg1:string):Promise<gui.TargetListResult>;

export function LoadActiveConfigToSession():Promise<gui.OperationResult>;

export function LoadRules(arg1:string,arg2:string):Promise<gui.OperationResult>;

export function QueryEventHistory(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:number,arg8:number):Promise<gui.EventHistoryResult>;

export function RenameConfig(arg1:number,arg2:string):Promise<gui.OperationResult>;

export function SaveConfig(arg1:number,arg2:string):Promise<gui.ConfigResult>;

export function SetActiveConfig(arg1:number):Promise<gui.OperationResult>;

export function SetDirty(arg1:boolean):Promise<void>;

export function SetMultipleSettings(arg1:string):Promise<gui.OperationResult>;

export function SetSetting(arg1:string,arg2:string):Promise<gui.OperationResult>;

export function StartSession(arg1:string):Promise<gui.SessionResult>;

export function StopSession(arg1:string):Promise<gui.SessionResult>;
