// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveRequest(arg1, arg2) {
  return window['go']['gui']['App']['ApproveRequest'](arg1, arg2);
}

export function ApproveResponse(arg1, arg2) {
  return window['go']['gui']['App']['ApproveResponse'](arg1, arg2);
}

export function AttachTarget(arg1, arg2) {
  return window['go']['gui']['App']['AttachTarget'](arg1, arg2);
}

export function DetachTarget(arg1, arg2) {
  return window['go']['gui']['App']['DetachTarget'](arg1, arg2);
}

export function DisableInterception(arg1) {
  return window['go']['gui']['App']['DisableInterception'](arg1);
}

export function EnableInterception(arg1) {
  return window['go']['gui']['App']['EnableInterception'](arg1);
}

export function GetCurrentSession() {
  return window['go']['gui']['App']['GetCurrentSession']();
}

export function GetRuleStats(arg1) {
  return window['go']['gui']['App']['GetRuleStats'](arg1);
}

export function ListTargets(arg1) {
  return window['go']['gui']['App']['ListTargets'](arg1);
}

export function LoadRules(arg1, arg2) {
  return window['go']['gui']['App']['LoadRules'](arg1, arg2);
}

export function Reject(arg1) {
  return window['go']['gui']['App']['Reject'](arg1);
}

export function StartSession(arg1) {
  return window['go']['gui']['App']['StartSession'](arg1);
}

export function StopSession(arg1) {
  return window['go']['gui']['App']['StopSession'](arg1);
}
