// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function ApproveRequest(arg1:string,arg2:string):Promise<gui.OperationResult>;

export function ApproveResponse(arg1:string,arg2:string):Promise<gui.OperationResult>;

export function AttachTarget(arg1:string,arg2:string):Promise<gui.OperationResult>;

export function DetachTarget(arg1:string,arg2:string):Promise<gui.OperationResult>;

export function DisableInterception(arg1:string):Promise<gui.OperationResult>;

export function EnableInterception(arg1:string):Promise<gui.OperationResult>;

export function GetCurrentSession():Promise<string>;

export function GetRuleStats(arg1:string):Promise<gui.StatsResult>;

export function ListTargets(arg1:string):Promise<gui.TargetListResult>;

export function LoadRules(arg1:string,arg2:string):Promise<gui.OperationResult>;

export function Reject(arg1:string):Promise<gui.OperationResult>;

export function StartSession(arg1:string):Promise<gui.SessionResult>;

export function StopSession(arg1:string):Promise<gui.SessionResult>;
